Fix: Enable accessKeysAuthentication to allow listKeys operation
Error: 'The ListKeys operation is not supported when access keys are disabled'
Solution: Change accessKeysAuthentication from 'Disabled' to 'Enabled'

We need accessKeysAuthentication='Enabled' because:
- We use data.azapi_resource_action.database_keys to retrieve keys
- listKeys operation requires access keys to be enabled
- This is needed for connection string outputs